from __future__ import annotations

from app.core.metrics import (
    HTTP_REQUESTS,
    HTTP_LATENCY,
    JOBS_CREATED,
    JOBS_FINISHED,
    QUEUE_DEPTH,
    SCHEDULED_DEPTH,
    IDEMPOTENCY_HITS,
    IDEMPOTENCY_MISSES,
    DLQ_MAINTENANCE_CYCLES,
    DLQ_MAINTENANCE_ELIGIBLE,
    DLQ_MAINTENANCE_TRIAGED_TOTAL,
    DLQ_MAINTENANCE_PURGED_TOTAL,
    DLQ_MAINTENANCE_ALERTS_TOTAL,
)

__all__ = [
    "HTTP_REQUESTS",
    "HTTP_LATENCY",
    "JOBS_CREATED",
    "JOBS_FINISHED",
    "QUEUE_DEPTH",
    "SCHEDULED_DEPTH",
    "IDEMPOTENCY_HITS",
    "IDEMPOTENCY_MISSES",
    "DLQ_MAINTENANCE_CYCLES",
    "DLQ_MAINTENANCE_ELIGIBLE",
    "DLQ_MAINTENANCE_TRIAGED_TOTAL",
    "DLQ_MAINTENANCE_PURGED_TOTAL",
    "DLQ_MAINTENANCE_ALERTS_TOTAL",
]
