"""
Pydantic Models and JSON Schemas for Learning Path (Blueprint Pattern)

This module defines:
- Request/Response models for Phase A (Unit Blueprint Generation)
- Request/Response models for Phase B (Node Content Generation)
- JSON Schema validators for anti-hallucination guardrails
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator
from enum import Enum


class NodeType(str, Enum):
    """Type of node in learning path"""
    lesson = "lesson"
    story = "story"
    checkpoint = "checkpoint"
    chest = "chest"


class UnitStatus(str, Enum):
    """Unit completion status"""
    locked = "locked"
    available = "available"
    in_progress = "in_progress"
    completed = "completed"


class NodeStatus(str, Enum):
    """Node completion status"""
    locked = "locked"
    available = "available"
    in_progress = "in_progress"
    completed = "completed"


# ==================== Phase A: Blueprint Generation ====================

class UserProfile(BaseModel):
    """User profile for personalized curriculum generation"""
    level: str = Field(..., description="CEFR level: A1, A2, B1, B2, C1, C2")
    interests: List[str] = Field(default_factory=list, description="Topics of interest")
    mastery_score: float = Field(default=0.5, ge=0.0, le=1.0, description="Current mastery score")
    weak_areas: List[str] = Field(default_factory=list, description="Topics needing reinforcement")
    target_lang: str = Field(..., description="Target language being learned")
    native_lang: str = Field(default="English", description="Native language")


class NodePreset(BaseModel):
    """
    Recipe/Blueprint for generating node content (Phase B).
    Stored in nodes.preset_json field.
    """
    type: NodeType = Field(..., description="Type of node")
    topic: str = Field(..., description="Main topic (must be from seed constants)")
    grammar_focus: Optional[str] = Field(None, description="Grammar point (must be from seed constants)")
    difficulty_delta: float = Field(default=0.0, description="Difficulty adjustment from baseline (-0.2 to +0.2)")
    vocabulary_level: str = Field(..., description="Vocabulary complexity: basic, intermediate, advanced")
    task_count: int = Field(default=7, ge=5, le=10, description="Number of tasks to generate")
    context: Optional[str] = Field(None, description="Contextual scenario for tasks")
    
    @field_validator("difficulty_delta")
    @classmethod
    def validate_difficulty_delta(cls, v):
        if not -0.2 <= v <= 0.2:
            raise ValueError("difficulty_delta must be between -0.2 and +0.2")
        return v


class BlueprintNode(BaseModel):
    """Node metadata in Unit blueprint"""
    type: NodeType
    preset: NodePreset
    order_index: int = Field(..., ge=0)


class UnitBlueprint(BaseModel):
    """
    Complete Unit blueprint generated by Phase A.
    This is what Gemini returns with temperature=0.2
    """
    title: str = Field(..., min_length=3, max_length=100)
    level_tag: str = Field(..., description="CEFR level tag")
    nodes: List[BlueprintNode] = Field(..., min_length=6, max_length=12)
    
    @field_validator("nodes")
    @classmethod
    def validate_progressive_difficulty(cls, nodes):
        """Ensure difficulty increases progressively"""
        if len(nodes) < 2:
            return nodes
        
        for i in range(1, len(nodes)):
            prev_diff = nodes[i-1].preset.difficulty_delta
            curr_diff = nodes[i].preset.difficulty_delta
            if curr_diff < prev_diff - 0.05:  # Allow small variations
                raise ValueError(f"Node {i} has lower difficulty than previous node")
        
        return nodes


class GenerateBlueprintRequest(BaseModel):
    """Request to generate Unit blueprint (Phase A)"""
    user_profile: UserProfile
    context: Optional[str] = Field(None, description="Additional context (e.g., 'after completing placement test')")


class GenerateBlueprintResponse(BaseModel):
    """Response after generating Unit blueprint"""
    unit_id: str
    title: str
    level_tag: str
    nodes_created: int
    status: UnitStatus


# ==================== Phase B: Content Generation ====================

class TaskDefinition(BaseModel):
    """Single task within a node"""
    id: str = Field(..., description="Unique task ID")
    type: str = Field(..., description="Task type: fill_blank, translate, choice, etc.")
    prompt: str = Field(..., description="Task prompt/question")
    solution: str = Field(..., description="Correct answer")
    distractors: Optional[List[str]] = Field(None, description="Wrong answers for multiple choice")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional task metadata")


class NodeContent(BaseModel):
    """Generated content for a node (Phase B output)"""
    node_id: str
    tasks: List[TaskDefinition] = Field(..., min_length=5, max_length=10)
    estimated_duration_minutes: int = Field(default=10)


class StartNodeRequest(BaseModel):
    """Request to start node and generate content (Phase B)"""
    node_id: str = Field(..., description="Node ID from blueprint")


class StartNodeResponse(BaseModel):
    """Response after starting node content generation"""
    job_id: str
    node_id: str
    status: str = "queued"
    status_url: str


# ==================== Seed Constants (Anti-Hallucination) ====================

class SeedConstants:
    """
    Hardcoded constants to prevent AI hallucinations.
    These define the allowed Topics, Grammar, and Skills.
    """
    
    TOPICS = {
        "A1": ["Greetings", "Family", "Food", "Colors", "Numbers", "Animals"],
        "A2": ["Shopping", "Travel", "Weather", "Hobbies", "Daily Routine", "Health"],
        "B1": ["Work", "Education", "Technology", "Environment", "Culture", "Media"],
        "B2": ["Business", "Politics", "Science", "Arts", "Economics", "Society"],
        "C1": ["Philosophy", "Psychology", "Literature", "Global Issues", "Innovation"],
        "C2": ["Advanced Discourse", "Specialized Domains", "Nuanced Expression"]
    }
    
    GRAMMAR = {
        "A1": ["Present Simple", "Present Continuous", "Articles", "Plurals", "Basic Pronouns"],
        "A2": ["Past Simple", "Future (going to)", "Comparatives", "Modal Verbs (can/must)", "Prepositions"],
        "B1": ["Present Perfect", "Past Continuous", "Conditionals (1st/2nd)", "Passive Voice", "Relative Clauses"],
        "B2": ["Present Perfect Continuous", "Past Perfect", "Conditionals (3rd)", "Reported Speech", "Mixed Conditionals"],
        "C1": ["Advanced Tenses", "Inversion", "Subjunctive", "Cleft Sentences", "Discourse Markers"],
        "C2": ["Subtle Modality", "Complex Syntax", "Stylistic Variation", "Pragmatic Competence"]
    }
    
    SKILLS = [
        "Vocabulary Acquisition",
        "Grammar Application",
        "Reading Comprehension",
        "Listening Comprehension",
        "Speaking Practice",
        "Writing Practice",
        "Translation",
        "Cultural Understanding"
    ]
    
    @classmethod
    def get_topics_for_level(cls, level: str) -> List[str]:
        """Get available topics for a CEFR level"""
        return cls.TOPICS.get(level, cls.TOPICS["A2"])
    
    @classmethod
    def get_grammar_for_level(cls, level: str) -> List[str]:
        """Get available grammar points for a CEFR level"""
        return cls.GRAMMAR.get(level, cls.GRAMMAR["A2"])
    
    @classmethod
    def validate_topic(cls, topic: str, level: str) -> bool:
        """Check if topic is valid for level"""
        return topic in cls.get_topics_for_level(level)
    
    @classmethod
    def validate_grammar(cls, grammar: str, level: str) -> bool:
        """Check if grammar is valid for level"""
        return grammar in cls.get_grammar_for_level(level)


# ==================== System Prompts ====================

class PromptTemplates:
    """System prompts for Phase A and Phase B"""
    
    @staticmethod
    def phase_a_blueprint(profile: UserProfile) -> str:
        """Generate system prompt for Phase A (Blueprint generation)"""
        level = profile.level
        topics = ", ".join(SeedConstants.get_topics_for_level(level))
        grammar = ", ".join(SeedConstants.get_grammar_for_level(level))
        interests = ", ".join(profile.interests) if profile.interests else "General"
        
        return f"""You are the Seed Curriculum Architect. Your role is to design a Unit blueprint for language learners.

**User Context:**
- Level: {level} (CEFR)
- Interests: {interests}
- Current Mastery Score: {profile.mastery_score:.2f}
- Weak Areas: {', '.join(profile.weak_areas) if profile.weak_areas else 'None'}
- Target Language: {profile.target_lang}
- Native Language: {profile.native_lang}

**Available Topics:** {topics}
**Available Grammar:** {grammar}

**Your Task:**
Generate a Unit with 10-12 nodes that progressively increase in difficulty. Each node should:
1. Use ONLY topics and grammar from the lists above
2. Increase difficulty by 5% relative to previous node
3. Start at difficulty_delta relative to mastery_score ({profile.mastery_score:.2f})
4. Include variety: lessons, stories, checkpoints, and reward chests

**Output Format (STRICT JSON):**
{{
  "title": "Unit title based on {interests}",
  "level_tag": "{level}",
  "nodes": [
    {{
      "type": "lesson",
      "order_index": 0,
      "preset": {{
        "type": "lesson",
        "topic": "TopicFromList",
        "grammar_focus": "GrammarFromList",
        "difficulty_delta": -0.1,
        "vocabulary_level": "basic",
        "task_count": 7,
        "context": "Brief scenario"
      }}
    }},
    ...
  ]
}}

**Constraints:**
- Generate ONLY valid JSON
- NO explanations or markdown
- Difficulty must increase progressively
- All topics/grammar must be from provided lists"""
    
    @staticmethod
    def phase_b_content(preset: NodePreset, target_lang: str, native_lang: str) -> str:
        """Generate system prompt for Phase B (Content generation)"""
        return f"""You are the Seed Content Manager. Generate engaging language learning tasks.

**Node Recipe:**
- Type: {preset.type}
- Topic: {preset.topic}
- Grammar Focus: {preset.grammar_focus or 'None'}
- Difficulty Adjustment: {preset.difficulty_delta:+.2f}
- Vocabulary Level: {preset.vocabulary_level}
- Task Count: {preset.task_count}
- Context: {preset.context or 'General practice'}

**Languages:**
- Target Language: {target_lang}
- Native Language: {native_lang}

**Your Task:**
Generate {preset.task_count} varied tasks following the recipe. Tasks should:
1. Be creative and engaging
2. Match the difficulty level (delta: {preset.difficulty_delta:+.2f})
3. Focus on {preset.topic} with {preset.grammar_focus or 'varied grammar'}
4. Use {preset.vocabulary_level} vocabulary
5. NOT hallucinate facts or cultural details
6. Be culturally neutral unless specified

**Task Types to Include:**
- fill_blank: Fill in missing words
- translate: Translate sentences
- choice: Multiple choice questions
- reorder: Arrange words/sentences correctly
- match: Match pairs (words/definitions)

**Output Format (STRICT JSON):**
{{
  "tasks": [
    {{
      "id": "task_1",
      "type": "fill_blank",
      "prompt": "Complete: Je ____ au marché.",
      "solution": "vais",
      "distractors": ["vas", "va", "vont"],
      "metadata": {{"hint": "Present tense of 'aller'"}}
    }},
    ...
  ]
}}

**Quality Requirements:**
- Linguistic accuracy
- Appropriate difficulty
- Clear instructions
- Engaging content
- NO fabricated facts"""
