from __future__ import annotations

from typing import Any, Protocol


class AsyncPipelineProtocol(Protocol):
    def incr(self, key: str) -> Any: ...
    def ttl(self, key: str) -> Any: ...
    async def execute(self) -> list[Any]: ...


class AsyncCacheProtocol(Protocol):
    async def get(self, key: str) -> Any: ...
    async def set(self, key: str, value: Any, *, ex: int | None = None, nx: bool | None = None) -> Any: ...
    async def setex(self, key: str, ttl: int, value: Any) -> Any: ...
    async def delete(self, *keys: str) -> Any: ...
    async def incr(self, key: str) -> Any: ...
    async def ttl(self, key: str) -> Any: ...
    async def expire(self, key: str, ttl: int) -> Any: ...
    def pipeline(self) -> AsyncPipelineProtocol: ...
    async def eval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...
