from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Iterable, Protocol


class DatabaseProtocol(Protocol):
    """Synchronous database access protocol for Core services."""

    def transaction(self) -> AbstractContextManager: ...

    def execute(self, sql: str, params: tuple[Any, ...] = ()) -> None: ...

    def executemany(self, sql: str, seq: Iterable[tuple[Any, ...]]) -> None: ...

    def fetchone(self, sql: str, params: tuple[Any, ...] = ()) -> Any | None: ...

    def fetchall(self, sql: str, params: tuple[Any, ...] = ()) -> list[Any]: ...

    def close(self) -> None: ...


class AsyncDatabaseProtocol(Protocol):
    """Async database access protocol for Core services."""

    async def fetchrow(self, query: str, *args: Any): ...
    async def fetch(self, query: str, *args: Any): ...
    async def fetchval(self, query: str, *args: Any): ...
    async def execute(self, query: str, *args: Any): ...
    def transaction(self): ...
